name: dbt Production Deploy

on:
  push:
    branches: [main, master]
    paths:
      - 'models/**'
      - 'macros/**'
      - 'tests/**'
      - 'seeds/**'
      - 'snapshots/**'
      - 'dbt_project.yml'
      - 'packages.yml'

jobs:
  dbt-production:
    runs-on: ubuntu-latest
    
    env:
      DBT_PROFILES_DIR: .
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > keyfile.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/keyfile.json" >> $GITHUB_ENV

      - name: Update profiles.yml with credentials
        run: |
          sed -i 's|/path/to/your/keyfile.json|'"$(pwd)/keyfile.json"'|g' profiles.yml

      - name: Install dbt packages
        run: dbt deps

      - name: Check dbt configuration
        run: dbt debug

      - name: Run dbt seeds
        run: dbt seed --target dev

      - name: Run dbt models
        run: dbt run --target dev

      - name: Run dbt tests
        run: dbt test --target dev

      - name: Run dbt snapshots
        run: dbt snapshot --target dev
        continue-on-error: true

      - name: Generate documentation
        run: dbt docs generate --target dev

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dbt-docs
          path: target/

      - name: Notify deployment success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const output = `
            🚀 **dbt Production Deployment Successful**
            
            **Branch**: ${{ github.ref_name }}
            **Commit**: ${{ github.sha }}
            **Timestamp**: ${{ github.event.head_commit.timestamp }}
            
            **Deployed components**:
            - ✅ Seeds loaded
            - ✅ Models built
            - ✅ Tests passed
            - ✅ Snapshots updated
            - ✅ Documentation generated
            
            **Target Environment**: Production (dev dataset)
            `;
            
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: output
            });
